# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NevaSampleTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NevaSampleTask
pod 'Alamofire'
pod 'AlamofireObjectMapper','~>5.0.0'
pod 'SDWebImage'

  target 'NevaSampleTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NevaSampleTaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
